apps/characters/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',
         views.CharacterListView.as_view(),
         name='character-list'),
    path('new/',
         views.CharacterCreateView.as_view(),
         name='character-create'),
    path('<slug:page_name>/',
         views.CharacterDetailView.as_view(),
         name='character-detail'),
]

project_senpals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.senpals.urls')),
    path('characters/', include('apps.characters.urls')),
    path('chats/', include('apps.chats.urls')),
    path('verses/', include('apps.verses.urls')),
    path('threads/', include('apps.threads.urls')),
    path('posts/', include('apps.posts.urls')),
    path('icons/', include('apps.icons.urls')),
    # path('wireframe/', include('apps.wireframe.urls')), # for testing new layouts/etc, not in use
]

apps/characters/models.py
from django.forms import ModelForm
from django.urls import reverse
from apps.senpals.models import *
from apps.verses.models import Verse


class Character(Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='characters', blank=True)
    name = models.CharField(max_length=100)
    page_name = models.SlugField(max_length=25, unique=True)
    tagline = models.CharField(max_length=25, default='', blank=True)
    description = models.TextField(blank=True)
    icon = models.URLField(default='', blank=True)
    header_image = models.URLField(default='', blank=True)

    def __str__(self):
        return self.page_name

    class Meta:
        ordering = ['page_name']

    def get_absolute_url(self):
        return reverse('character-detail', kwargs={'page_name': self.page_name})

    def get_threads(self):
        threads = list()
        for reply in self.replies.all():
            if reply.thread not in threads:
                threads.append(reply.thread)
        return threads


class CharacterCreateForm(ModelForm):
    class Meta:
        model = Character
        fields = ['page_name', 'name', 'tagline', 'description', 'icon', 'header_image']

apps/characters/forms.py
from django.forms import ModelForm
from .models import Character

apps/characters/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .models import *
from .forms import *


class CharacterListView(ListView):
    model = Character
    template_name = 'wireframe/characters/character_list_page.html'

    def get_queryset(self):
        return Character.objects.order_by('page_name')


class CharacterDetailView(DetailView):
    model = Character
    template_name = 'wireframe/characters/character_detail_page.html'
    slug_field = 'page_name'
    slug_url_kwarg = 'page_name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CharacterCreateView(CreateView):
    model = Character
    form_class = CharacterCreateForm
    template_name = 'characters/character_create_page.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

apps/characters/templates/characters/character_create_form.html
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
            <script>
                $("#{{ field.id_for_label }}").addClass('form-control');
            </script>
        </div>
    {% endfor %}
    <input class="btn btn-primary btn-sm btn-info" type="submit" value="Submit" />
</form>

apps/characters/templates/characters/character_create_page.html
{% extends "senpals/base.html" %}
{% block title %}New Character{% endblock %}
{% block navbar %}{% include "senpals/navbar.html" with nav_title="New Character"%}{% endblock %}
{% block body %}
    <div class="card ml-auto mr-auto" style="margin-top: 75px;">
        <div class="card-body">
            {% include 'characters/character_create_form.html' %}
        </div>
    </div>
{% endblock %}

apps/characters/templates/characters/character_detail_page.html
{#{% extends "senpals/base.html" %}#}
{##}
{#{% block title %}{{ character.page_name }}{% endblock %}#}
{##}
{#{% block navbar %}{% include "senpals/navbar.html" with nav_title=character.page_name %}{% endblock %}#}
{##}
{#{% block body %}#}
{#<div class="container">#}
{#    <div class="row mt-5">#}
{#        {% include 'characters/character_info_card.html' %}#}
{#        {% include 'characters/character_tabs_card.html' %}#}
{#    </div>#}
{#</div>#}
{#{% include 'characters/character_info_update_modal.html' %}#}
{#{% include 'characters/character_description_update_modal.html' %}#}
{#{% endblock %}#}

apps/characters/templates/characters/character_info_card.html
<div class="card card-profile col-2 mt-5 ml-auto mr-auto align-self-start" lang="en" style="min-width: 250px;">
    <div class="card-header card-header-image">
        <img src="{{ character.header_image }}" style="max-width: 200px; background-color: lightgray;" alt=""/>
    </div>
    <div class="card-body">
        <h4 class="mb-0 card-title text-muted">{{ character.name }}</h4>
        <h6 class="mt-1 mb-0 card-subtitle text-muted"><a href="{% url 'user-profile' username=character.user.username %}">{{ character.user.username }}</a></h6>
        <p class="card-category text-gray mb-1 mt-0">{{ character.tagline|lower }}</p>
        <a href="{% url 'character-wire' page_name=character.page_name %}">Wireframe preview</a>
        <p class="mb-0"><a href="#" data-toggle="modal" data-target="#infoModal"><i class="material-icons mr-1" style="margin-bottom: -0px;">edit</i></a>
    </div>
</div>

apps/characters/templates/characters/character_info_update_modal.html
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="infoModalLabel">Edit {{ character.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{% url 'character-info-update' page_name=character.page_name %}" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="modal-body">
                    {{ info_form.as_p }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <input type="submit" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

apps/characters/templates/characters/character_list_item.html
<div class="card card-profile mb-4 ml-auto mr-auto ml-sm-4 mr-sm-4" style="min-width: 200px; max-width: 200px;">
  <div class="card-header card-header-image">
        <a href="{% url 'character-detail' page_name=character.page_name %}">
            <img class="text-left" src="{{ character.icon }}" style="width: 100px; height: 100px;">
        </a>
    </div>
    <div class="card-body">
        <p class="card-title"><strong>{{ character.name }}</strong></p>
        <a class="badge badge-primary" href="{% url 'character-detail' page_name=character.page_name %}">{{ character.page_name }}</a>
        <h6 class="card-category text-gray mt-2 mb-1">{{ character.tagline }}</h6>
    </div>
</div>

apps/characters/templates/characters/character_list_page.html
{% extends "senpals/base.html" %}

{% block title %}Characters{% endblock %}

{% block navbar %}
    {% include "senpals/navbar.html" with nav_title="Characters" %}
{% endblock %}



{% block body %}
    <h3 class="title text-center"><a  href="{% url 'character-create' %}">New Character <i class="material-icons">add_circle_outline</i></a></h3>
    {% include "characters/character_list.html" %}
{% endblock %}

apps/characters/templates/characters/character_note_create_form.html
{% with form=character.get_note_form %}
    <div class="ml-3 mr-3">
        <form method="post" enctype="multipart/form-data" action="{% url 'character-note-create' page_name=character.page_name %}">
            {% csrf_token %}
            <input type="hidden" id="{{ form.character.id_for_label }}" name="{{ form.character.html_name }}" value="{{ character.pk }}" />
            <div class="form-group">
                {{ form.verse.errors }}
                <label for="{{ form.verse.id_for_label }}">Verse:</label>
                {{ form.verse }}
            </div>
            <div class="form-group">
                {{ form.text.errors }}
                <label for="summernote">Text:</label>
                <textarea id="summernote" name="{{ form.text.html_name }}"></textarea>
                <hr>
            </div>
            <div class="form-group">
                {{ form.tags.errors }}
                <label for="{{ form.tags.id_for_label }}">Tags:</label>
                <input type="text" placeholder="#" class="tagsinput form-control" data-role="tagsinput" data-color="info" id="{{ form.tags.id_for_label }}" name="{{ form.tags.html_name }}" />
            </div>
            <div class="form-group">
                <input class="btn btn-primary btn-sm" type="submit" />
            </div>
        </form>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                airMode: true,
                popover: {
                    air: [
                        ['font', ['bold', 'italic', 'underline', 'clear']],
                    ]
                },
            });
        });
    </script>
{% endwith %}

apps/characters/templates/characters/character_tab_description.html
<div class="tab-pane active" id="description">
    <h3 class="title text-center"><a href="#" data-toggle="modal" data-target="#descriptionModal">Edit Description <i class="material-icons">edit</i></a></h3>
    <hr class="mb-0">
    {% if character.description|length > 0 %}
        <div class="p-4 ">
            {{ character.description|safe }}
        </div>
    {% else %}
        <p class="mt-4"><em>No description found.</em></p>
    {% endif %}
</div>

apps/characters/templates/characters/character_tab_posts.html
<div class="tab-pane active" id="posts">
    <div>
        {% if character.posts.count > 0 %}
            {% for post in character.posts.all %}
                <div class="card-body">
                    <h2 class="card-title"><a href="{% url 'post-detail' pk=post.pk %}">{{ post.title }}</a></h2>
                    <hr class="mt-0 ml-3 mr-3">
                    {% if post.verse %}<h6 class="card-subtitle mt-2 mb-2"><a href="{% url 'verse-detail' pk=post.verse.pk %}">{{ post.verse.name }}</a></h6>{% endif %}
                    {{ post.text|safe|truncatechars_html:500 }}
                    {% if post.text|length > 500 %}<h6 class="card-subtitle mb-3 float-right"><a href="{% url 'post-detail' pk=post.pk %}">Read More</a></h6>{% endif %}
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-2"><em>No posts found.</em></p>
        {% endif %}
    </div>
</div>

apps/characters/templates/characters/character_tab_traits.html
{% load static %}
<div class="card-body">
    <div id="accordion">
        <div class="card-collapse mb-5">
            <div class="card-header" role="tab" id="newTraitHeading">
                <h6>
                    <a data-toggle="collapse" href="#newTrait" aria-expanded="false" aria-checked="newTrait">
                        New Trait
                        <i class="material-icons">keyboard_arrow_down</i>
                    </a>
                </h6>
            </div>
            <div id="newTrait" class="collapse" role="tabpanel" aria-labelledby="newTraitHeading" data-parent="#accordion">
                <div class="card-body">
                    {% include 'characters/character_trait_create_form.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="toolbar">
    </div>
    <div class="material-datatables ml-auto mr-auto">
        <table id="datatables" data-page-length='25' data-order='[[ 0, "asc" ]]' class="table table-condensed table-hover" cellspacing="0">
            <thead>
                <tr>
                    <th>Verse</th>
                    <th>Trait</th>
                    <th class="sorting_asc_disabled sorting_desc_disabled disabled"></th>
                    <th class="sorting_asc_disabled sorting_desc_disabled disabled"></th>
                    <th class="sorting_asc_disabled sorting_desc_disabled disabled"></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Verse</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </tfoot>
            <tbody>
                {% for trait in character.traits.all %}
                    <tr>
                        {% if trait.verses %}
                            {% if trait.verses.count == 1 %}
                                <td data-order="name">
                            {% else %}
                                <td data-order="">
                            {% endif %}
                            {% for verse in trait.verses.all|dictsort:"name" %}
                                <p class="m-0"><span class="badge badge-sm badge-info"><a class="text-white" href="{% url 'verse-detail' pk=verse.pk %}">{{ verse.name }}</a></span></p>
                            {% endfor %}
                            </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td class="text-right align-top">
                            <small><strong class="mr-2">{{ trait.title }}</strong></small>
                        </td>
                        <td class="text-left align-top">
                            <small>{{ trait.value }}</small>
                        </td>
                        <td class="align-top">
                            <a href="#"><i class="material-icons btn-sm">edit</i></a>
                        </td>
                        <td class="align-top">
                            <a href="#"><i class="material-icons btn-sm">delete</i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [25, 50, 100, -1],
                [25, 50, 100, "All"]
            ],
            responsive: false,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

        var table = $('#datatable').DataTable();

        // Edit record
        table.on('click', '.edit', function() {
        $tr = $(this).closest('tr');
        var data = table.row($tr).data();
        alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function(e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function() {
            alert('You clicked on Like button');
        });
    });
</script>

apps/characters/templates/characters/character_tabs_card.html
{#<div class="card card-nav-tabs col-9 ml-auto mr-auto mt-5 align-self-start">#}
{#    {% include 'characters/character_tabs_nav.html' %}#}
{#    <div class="card-body">#}
{#        <div class="tab-content">#}
{#            {% include 'characters/character_tab_description.html' %}#}
{#            {% include 'characters/character_tab_traits.html' %}#}
{#            {% include 'characters/character_tab_notes.html' %}#}
{#            {% include 'characters/character_tab_posts.html' %}#}
{#            {% include 'characters/character_tab_threads.html' %}#}
{#        </div>#}
{#    </div>#}
{#</div>#}

apps/characters/templates/characters/character_tabs_nav.html
<div class="card-header card-header-primary">
    <div class="nav-tabs-wrapper">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link {{ active_desc }}" href="{% url 'character-detail' page_name=character.page_name %}"><i class="material-icons">face</i>  Description</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ active_traits }}" href="{% url 'character-detail-traits' page_name=character.page_name %}"><i class="material-icons">assignment_ind</i> Traits</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ active_notes }}" href="{% url 'character-detail-notes' page_name=character.page_name %}"><i class="material-icons">notes</i>  Notes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ active_posts }}" href="{% url 'character-detail-posts' page_name=character.page_name %}"><i class="material-icons">description</i>  Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ active_threads }}" href="{% url 'character-detail-threads' page_name=character.page_name %}" ><i class="material-icons">list</i> Threads</a>
            </li>
        </ul>
    </div>
</div>

apps/characters/templates/characters/character_trait_create_form.html
{% with form=character.get_trait_form %}
    <div class="ml-3 mr-3">
        <form method="post" enctype="multipart/form-data" action="{% url 'character-trait-create' page_name=character.page_name %}">
            {% csrf_token %}
            <input type="hidden" id="{{ form.character.id_for_label }}" name="{{ form.character.html_name }}" value="{{ character.pk }}" />
            <div class="form-group">
                {{ form.verses.errors }}
                <label for="{{ form.verses.id_for_label }}"><strong>Verse</strong>:</label>
                {{ form.verses }}
            </div>
            <div class="row">
                <div class="form-group col-4 ml-3">
                    {{ form.title.errors }}
                    <label for="{{ form.title.id_for_label }}"><strong>Trait</strong>:</label>
                    <input type="text" placeholder="e.g. Birthday" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}" />
                </div>
                <div class="form-group col">
                    {{ form.value.errors }}
                    <label for="{{ form.value.id_for_label }}"><strong>Value</strong>:</label>
                    <input placeholder="e.g. 15 July" type="text" class="form-control" id="{{ form.value.id_for_label }}" name="{{ form.value.html_name }}" />
                </div>
            </div>
            <input class="btn-sm btn btn-primary" type="submit" />
        </form>
    </div>
{% endwith %}