apps/threads/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',
         views.ThreadListView.as_view(),
         name='thread-list'),
    path('new/',
         views.ThreadCreateView.as_view(),
         name='thread-create'),
    path('<int:pk>/',
         views.ThreadDetailView.as_view(),
         name='thread-detail'),
    path('<int:pk>/edit/',
         views.ThreadUpdateView.as_view(),
         name='thread-update'),
    path('<int:pk>/delete/',
         views.ThreadDeleteView.as_view(),
         name='thread-delete'),
    path('<int:pk>/replies/new/',
         views.ReplyCreateView.as_view(),
         name='reply-create'),
    path('<int:thread_pk>/replies/<int:pk>/update/',
         views.ReplyUpdateView.as_view(),
         name='reply-update'),
    path('<int:thread_pk>/replies/<int:pk>/delete/',
         views.ReplyDeleteView.as_view(),
         name='reply-delete'),
]

project_senpals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.senpals.urls')),
    path('characters/', include('apps.characters.urls')),
    path('chats/', include('apps.chats.urls')),
    path('verses/', include('apps.verses.urls')),
    path('threads/', include('apps.threads.urls')),
    path('posts/', include('apps.posts.urls')),
    path('icons/', include('apps.icons.urls')),
    # path('wireframe/', include('apps.wireframe.urls')), # for testing new layouts/etc, not in use
]

apps/threads/models.py
from django.db import models
from django.urls import reverse
from apps.senpals.models import Model, User
from apps.verses.models import Verse
from apps.characters.models import Character
from django.forms import ModelForm
from django import forms
from django.forms.widgets import HiddenInput, Textarea


# thread models & forms
class Thread(Model):
    user = models.ForeignKey(User, related_name='starters', blank=True, on_delete=models.DO_NOTHING, null=True)
    title = models.CharField(max_length=255, default='Untitled', blank=True)
    verse = models.ForeignKey(Verse, related_name='threads', blank=True, null=True, on_delete=models.DO_NOTHING)
    caption = models.CharField(max_length=255, default='', blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('thread-detail', kwargs={'pk': self.pk})

    def get_update_form(self):
        return ThreadUpdateForm(instance=self)

    def get_reply_form(self):
        return ReplyCreateForm(initial={'thread': self})

    def get_characters(self):
        characters = list()
        for reply in self.replies.all():
            if reply.character not in characters:
                characters.append(reply.character)
        characters.sort(key=lambda x: x.page_name)
        return characters

    def get_latest_reply(self):
        return self.replies.order_by('created').last()


class ThreadCreateForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    verse = forms.ModelChoiceField(queryset=Verse.objects.all(), required=False)
    caption = forms.CharField(max_length=255, required=False)
    character = forms.ModelChoiceField(queryset=Character.objects.all())
    text = forms.TextInput()


class ThreadUpdateForm(ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'verse', 'caption']


# reply model & forms
class Reply(Model):
    character = models.ForeignKey(Character, related_name='replies', on_delete=models.DO_NOTHING, null=True)
    thread = models.ForeignKey(Thread, related_name='replies', on_delete=models.CASCADE)
    text = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Replies'
        ordering = ['created']

    def get_update_form(self):
        return ReplyUpdateForm(self)

    def __str__(self):
        return f"Reply by {self.character.page_name} to {self.thread.title}"


class ReplyCreateForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['thread', 'character', 'text']

        widgets = {
            'thread': HiddenInput(),
            'text': Textarea()
        }


class ReplyUpdateForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['text']

apps/threads/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import *
from django.urls import reverse_lazy


class ThreadCreateView(FormView):
    template_name = 'threads/thread_create_page.html'
    form_class = ThreadCreateForm

    def form_valid(self, form):
        thread = self.create_thread(form, self.request.user)
        self.create_reply(form, thread)
        self.success_url = reverse_lazy('thread-detail', kwargs={'pk': thread.pk})
        return super().form_valid(form)

    def create_thread(self, form, user):
        if form.fields['verse']:
            verse = form.cleaned_data['verse']
        else:
            verse = None
        thread = Thread.objects.create(
            user=user,
            title=form.cleaned_data['title'],
            verse=verse,
            caption=form.cleaned_data['caption']
        )
        thread.save()
        return thread

    def create_reply(self, form, thread):
        reply = Reply.objects.create(
            character=form.cleaned_data['character'],
            thread=thread,
            text=form.cleaned_data['text']
        )
        reply.save()


class ThreadListView(ListView):
    model = Thread
    template_name = 'threads/thread_list_page.html'


class ThreadDetailView(DetailView):
    model = Thread
    template_name = 'wireframe/threads/thread_detail_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reply_form'] = self.object.get_reply_form()
        return context


class ThreadUpdateView(UpdateView):
    model = Thread
    form_class = ThreadUpdateForm

    def post(self, request, *args, **kwargs):
        pk = kwargs['pk']
        self.success_url = reverse('thread-detail', kwargs={'pk': pk})
        return super().post(self)


class ThreadDeleteView(DeleteView):
    model = Thread
    success_url = reverse_lazy('thread-list')


class ReplyCreateView(CreateView):
    model = Reply
    form_class = ReplyCreateForm
    thread = None

    def post(self, request, *args, **kwargs):
        pk = kwargs['pk']
        self.success_url = reverse_lazy('thread-detail', kwargs={'pk': pk})
        return super().post(self)

    def form_valid(self, form):
        return super().form_valid(form)


class ReplyUpdateView(UpdateView):
    model = Reply
    form_class = ReplyUpdateForm
    template_name = "senpals/form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('thread-detail', kwargs={'pk': kwargs['thread_pk']})
        return super().post(self)


class ReplyDeleteView(DeleteView):
    model = Reply

    def post(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('thread-detail', kwargs={'pk': kwargs['thread_pk']})
        return super().post(self)

apps/threads/templates/threads/reply.html
<div class="card col-md-10 col-xl-8 ml-auto mr-auto mt-5 mb-5 pl-4 pr-4">
    <div class="card-header card-header-image">
        <img class="img" src="{{ reply.character.icon }}" style="width: 100px; height: 100px;"/>
        <h4 class="card-title" style="margin-left: 100px;"><a class="btn btn-sm btn-primary" href="{% url 'character-detail' page_name=reply.character.page_name %}">{{ reply.character.page_name }}</a></h4>
    </div>
    <div class="card-body" id="reply_{{ reply.pk }}">
        {{ reply.text|safe }}
    </div>
    <hr class="m-0" />
    <div class="card-footer">
        <div class="stats"><i class="material-icons mr-2">access_time</i> <em>{{ reply.created }}</em></div>
        <div class="stats">
            <a class="text-secondary" href="{% url 'reply-update' thread_pk=thread.pk pk=reply.pk %}"><i id="reply_{{ reply.pk }}_edit" class="material-icons align-top" >edit</i></a>
            <a class="text-secondary" data-toggle="modal" data-target="#deleteReplyModal" data-reply="{{ reply.pk }}"><i id="reply_{{ reply.pk }}_delete" class="material-icons align-top">delete</i></a>
        </div>
    </div>
</div>

apps/threads/templates/threads/reply_create.html
<div class="card-plain col-md-10 col-xl-8 ml-auto mr-auto mt-5 mb-5 pl-4 pr-4">
    <form method="post" action="{% url 'reply-create' pk=thread.pk %}">
        {% csrf_token %}
        {{ reply_form.thread }}
        <div class="form-inline m-2">
            <label class="card-title mr-3" for="id_character">Reply with...</label>
{#            <label for="id_character">Character:</label>#}
{#            <select class="form-control ml-2" id="id_character" name="character">#}
{#                {% include 'senpals/user_character_options.html' %}#}
{#            </select>#}
            {{ reply_form.character }}
        </div>
        <div class="form-group mt-4">
            {{ reply_form.text }}
        </div>
{#        {{ reply_form.as_p }}#}


        <input class="btn btn-sm btn-primary" type="submit" />
    </form>
</div>

apps/threads/templates/threads/thread_create_page.html
{% extends "senpals/base.html" %}
{% block title %}New Thread{% endblock %}
{% block navbar %}{% include "senpals/navbar.html" with nav_title="New Thread"%}{% endblock %}
{% block body %}
    <div class="card col-md-6 ml-auto mr-auto" style="margin-top: 75px;">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                        <script>
                            $("#{{ field.id_for_label }}").addClass('form-control');
                        </script>
                    </div>
                {% endfor %}
                <input class="btn btn-primary btn-sm btn-info" type="submit" value="Submit" />
            </form>
        </div>
    </div>
{% endblock %}

apps/threads/templates/threads/thread_detail_page.html
{% extends "senpals/base.html" %}
{% load static %}

{% block links %}
    <link href="{% static 'summernote/summernote.css' %}" rel="stylesheet">
    <script src="{% static 'summernote/summernote-bs4.min.js' %}"></script>
{% endblock %}

{% block title %}{{ thread.title }}{% endblock %}
{% block navbar %}{% include "senpals/navbar.html" with nav_title=thread.title %}{% endblock %}


{% block body %}
{#    <hr class="mr-5 ml-5 pr-5 pl-5 mt-5 mb-5" />#}
    <blockquote class="blockquote mr-5 ml-5 mt-4 text-center">
        {{ thread.caption }}
        <footer class="blockquote-footer mb-0 mt-2">
            {% for character in thread.get_characters %}
                <a href="{% url 'character-detail' page_name=character.page_name %}">{{ character.page_name }}</a>
                {% if character != thread.get_characters|last %}
                    &
                {% endif %}
            {% endfor %}
        </footer>
        {% if thread.verse %}<div><a class="badge badge-sm badge-primary" href="{% url 'verse-detail' pk=thread.verse.pk %}">{{ thread.verse.name }}</a></div>{% endif %}
        <div class="ml-auto mr-auto text-center"><a class="" data-toggle="modal" data-target="#updateThread"><i style="font-size: 16px;" class="material-icons">edit</i></a> <a data-toggle="modal" data-target="#confirmDeleteModal"><i style="font-size: 16px;" class="material-icons">delete</i></a></div>
    </blockquote>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mt-5" style="margin-bottom: -40px;">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
    {% for reply in thread.replies.all %}
        {% include "threads/reply.html" %}
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mb-5" style="margin-top: -40px;">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>

    {% include "threads/reply_create.html" %}


    <!-- Modal -->
    <div class="modal fade" id="updateThread" tabindex="-1" role="dialog" aria-labelledby="updateThreadLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateThreadLabel">Edit Thread</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body">
                    {% include "threads/thread_update.html" %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Are you sure you want to delete this thread?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center pb-0">
                    <form action="{% url 'thread-delete' pk=thread.pk %}" method="post">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" value="delete" class="btn btn-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteReplyModal" tabindex="-1" role="dialog" aria-labelledby="deleteReplyModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteReplyModalLabel">Are you sure you want to delete this reply?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center pb-0">
                    <form id="deleteReplyForm" method="post">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" value="delete" class="btn btn-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('#deleteReplyModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var reply = button.data('reply') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('#deleteReplyForm').attr('action', `replies/${reply}/delete/`)
        })
    </script>
{% endblock %}

apps/threads/templates/threads/thread_list.html
{% load static %}
<div class="card-body">
    <div class="toolbar">
    </div>
    <div class="material-datatables">
        <table id="datatables" data-page-length='15' data-order='[[ 1, "desc" ]]' class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Last Reply</th>
                    <th>Created</th>
                    <th>Verse</th>
                    <th><i class="material-icons" style="margin-bottom: -0px;">reply</i></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Title</th>
                    <th>Last Reply</th>
                    <th>Created</th>
                    <th>Verse</th>
                    <th><i class="material-icons" style="margin-bottom: -0px;">reply</i></th>
                </tr>
            </tfoot>
            <tbody>
                {% for thread in thread_list %}
                    {% include "threads/thread_list_item.html" %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script src="{% static 'senpals/assets/js/plugins/jquery.datatables.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [15, 25, 50, -1],
                [15, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });
        var table = $('#datatable').DataTable();
    });
</script>

apps/threads/templates/threads/thread_list_item.html
<tr>
    <td><small><strong><a href="{% url 'thread-detail' pk=thread.pk %}">{{ thread.title }}</a></strong></small></td>
    <td data-order="{{ thread.get_latest_reply.created|date:'ymdhi' }}"><small>{{ thread.get_latest_reply.created|date:'m/d/y, h:i a' }} by <strong><a href="{% url 'character-detail' page_name=thread.get_latest_reply.character.page_name %}">{{ thread.get_latest_reply.character.page_name }}</a></strong></small></td>
    <td data-order="{{ thread.created|date:'ymdhi' }}"><small>{{ thread.created|date:'m/d/y, h:i a' }}</small></td>
    <td>{% if thread.verse %}<small><a href="{% url 'verse-detail' pk=thread.verse.pk %}">{{ thread.verse.name }}</a></small>{% endif %}</td>
    <td><small><strong>{{ thread.replies.count }}</strong></small></td>
</tr>

apps/threads/templates/threads/thread_list_page.html
{% extends "senpals/base.html" %}
{% load static %}

{% block links %}
    <script src='{% static "senpals/assets/js/plugins/jquery.dataTables.min.js" %}'></script>
{% endblock %}

{% block title %}Threads{% endblock %}

{% block navbar %}{% include "senpals/navbar.html" with nav_title="Threads" %}{% endblock %}

{% block body %}
    <div id="top" class="header text-center mt-4 mb-0 p-2">
        <h3 class="title"> <a class href="{% url 'thread-create' %}">New Thread <i class="material-icons" style="margin-bottom: 0;">add_circle_outline</i></a></h3>
    </div>
    <hr>
    {% include "threads/thread_list.html" %}
{% endblock %}

apps/threads/templates/threads/thread_update.html
<form method="post" action="{% url 'thread-update' pk=thread.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in thread.get_update_form %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
            <script>
                $("#{{ field.id_for_label }}").addClass('form-control');
            </script>
        </div>
    {% endfor %}
    <input class="btn btn-primary btn-sm btn-info" type="submit" value="Submit" />
</form>